name: Deploy MuleSoft Application to CloudHub 2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>cloudhub2</id>
                <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
              </server>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.ANYPOINT_CLIENT_ID }}</username>
                <password>${{ secrets.ANYPOINT_CLIENT_SECRET }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build JAR
        run: mvn clean package -DmuleDeploy

  deploydev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>cloudhub2</id>
                <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
              </server>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.ANYPOINT_CLIENT_ID }}</username>
                <password>${{ secrets.ANYPOINT_CLIENT_SECRET }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Deploy to dev
        run: |
          mvn deploy -DmuleDeploy -DskipMunitTests \
          -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
          -Denv="${{ secrets.ENV }}" \
          -Dappname="${{ secrets.APP_NAME }}"

  deployuat:
    needs: deploydev
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>cloudhub2</id>
                <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
              </server>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.ANYPOINT_CLIENT_ID }}</username>
                <password>${{ secrets.ANYPOINT_CLIENT_SECRET }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Deploy to uat
        run: |
          mvn deploy -DmuleDeploy -DskipMunitTests \
          -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
          -Denv="${{ secrets.ENV }}" \
          -Dappname="${{ secrets.APP_NAME }}"
